services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py
    ports:
      - "8010:8010"
    volumes:
      - .:/code
    links:
      - redis
      - db
      - check_service
    depends_on:
      redis:
          condition: service_started
      db:
          condition: service_healthy
      check_service:
          condition: service_started
    environment:
      - SRVC_LOG=etc/logging.conf


  check_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: check_service
    command: python3 check_service.py
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SRVC_LOG=etc/logging.conf


  redis:
    image: redis

  db:
    image: mysql
    ports:
      - "3306:33060"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pckg_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - ./dbdata:/var/lib/mysql/
